# dream_data.py

# Dream Symbolism
dream_symbolism = {
    "water": "Emotional depth and subconscious feelings.",
    "flying": "Desire for freedom or escape from a situation.",
    "snake": "Transformation, healing, or potential challenges.",
    "fire": "Passion, energy, or a burning desire.",
    "mirror": "Self-reflection and introspection.",
    "tree": "Personal growth and stability.",
    "island": "Isolation or a desire for solitude.",
    "clock": "Awareness of time and deadlines.",
    "celebration": "Joy, achievement, or a need for recognition.",
    "mask": "Hidden identity or disguise.",
    "rainbow": "Hope, positivity, and a promise of better things.",
    "abyss": "Facing the unknown or fear of the uncertain.",
    "garden": "Harmony, tranquility, and connection with nature.",
    "dove": "Peace, innocence, and spiritual significance.",
    "maze": "Feeling lost or navigating through complexities.",
    "tower": "Ambition, achievement, or a desire for success.",
    "shadow": "Unconscious aspects, hidden fears, or repressed desires.",
    "moon": "Feminine energy, intuition, and the passage of time.",
    "sun": "Masculine energy, vitality, and enlightenment.",
    "star": "Guidance, inspiration, and aspirations.",
    "mountain": "Obstacles, challenges, and the journey of self-discovery.",
    "forest": "Exploration of the unknown, subconscious, or hidden aspects of the self.",
    "beach": "Transition, relaxation, or the meeting point of the conscious and unconscious mind.",
    "road": "Life path, journey, or the direction of one's life.",
    "bridge": "Transition, connection, or overcoming obstacles.",
    "door": "Opportunity, access to new experiences, or the unknown.",
    "key": "Unlocking potential, opportunity, or gaining access to hidden knowledge.",
    "ship": "Journey, adventure, or navigating through life's challenges.",
    "sunset": "Endings, closure, or the completion of a cycle.",
    "sunrise": "New beginnings, hope, or the start of a new chapter.",
    "book": "Knowledge, learning, or the exploration of new ideas.",
    "dreamcatcher": "Protection from negative energies or the filtering of dreams.",
    "lantern": "Guidance, illumination, or seeking clarity in life.",
    "lighthouse": "Hope, guidance, or navigating through difficult times.",
    "compass": "Direction, guidance, or finding one's true path.",
    "starfish": "Regeneration, healing, or adaptability.",
    "whale": "Emotional depth, intuition, or the subconscious mind.",
    "butterfly": "Transformation, growth, or the emergence of one's true self.",
    "owl": "Wisdom, intuition, or the ability to see beyond illusions.",
    "spider": "Creativity, manifestation, or the weaving of one's destiny.",
    "dragonfly": "Change, adaptability, or the illusion of self-limitations.",
    "elephant": "Strength, wisdom, or the power to overcome obstacles.",
    "turtle": "Stability, patience, or the need to slow down and take things one step at a time.",
    "rose": "Love, passion, or the unfolding of one's inner beauty.",
    "thorn": "Challenges, pain, or the need to overcome obstacles to reach one's goals.",
    "crown": "Authority, power, or the recognition of one's own worth.",
    "sword": "Courage, strength, or the ability to cut through obstacles.",
    "shield": "Protection, defense, or the need to establish boundaries.",
    "anchor": "Stability, security, or the grounding of one's emotions.",
    "compass": "Guidance, direction, or finding one's true path.",
    "scales": "Balance, justice, or the need to weigh one's options.",
    "torch": "Guidance, enlightenment, or the pursuit of truth.",
    "treasure": "Hidden potential, abundance, or the discovery of one's true worth.",
    # Add more symbols and interpretations as needed
}


# Entity Patterns
patterns = [
    {"label": "DREAM_ACTION", "pattern": [{"LOWER": {"in": ["flying", "swooping", "grabbed", "carried"]}}]},
    {"label": "DREAM_LOCATION", "pattern": [{"LOWER": {"in": ["city", "skyscrapers", "forest", "cave"]}}]},
    {"label": "DREAM_CREATURE", "pattern": [{"LOWER": {"in": ["eagle", "lion", "dolphin", "unicorn", "dragon"]}}]},
    {"label": "DREAM_ELEMENT", "pattern": [{"LOWER": {"in": ["fire", "water", "tree", "island", "mirror", "rainbow", "dove"]}}]},
    {"label": "DREAM_OBJECT", "pattern": [{"LOWER": {"in": ["clock", "book", "key", "sword", "mask", "flower"]}}]},
    {"label": "DREAM_PERSON", "pattern": [{"LOWER": {"in": ["stranger", "friend", "teacher", "ancestor", "child"]}}]},
    {"label": "DREAM_FEELING", "pattern": [{"LOWER": {"in": ["joy", "fear", "love", "confusion", "excitement"]}}]},
    {"label": "DREAM_EVENT", "pattern": [{"LOWER": {"in": ["wedding", "battle", "chase", "discovery"]}}]},
    {"label": "DREAM_ANIMAL", "pattern": [{"LOWER": {"in": ["dog", "cat", "horse", "rabbit", "bear"]}}]},
    {"label": "DREAM_INSECT", "pattern": [{"LOWER": {"in": ["butterfly", "spider", "ant", "bee"]}}]},
    {"label": "DREAM_FOOD", "pattern": [{"LOWER": {"in": ["apple", "cake", "fish", "coffee", "pizza"]}}]},
    {"label": "DREAM_BODY_PART", "pattern": [{"LOWER": {"in": ["hand", "foot", "head", "heart"]}}]},
    {"label": "DREAM_COLOR", "pattern": [{"LOWER": {"in": ["red", "blue", "green", "yellow", "purple"]}}]},
    # Add more entity patterns as needed
    {"label": "DREAM_FEELING", "pattern": [{"LOWER": {"in": ["anger", "sadness", "happiness", "anxiety", "peace"]}}]},
    {"label": "DREAM_ELEMENT", "pattern": [{"LOWER": {"in": ["earth", "wind", "sky", "sun", "moon", "star"]}}]},
    {"label": "DREAM_OBJECT", "pattern": [{"LOWER": {"in": ["door", "window", "car", "phone", "computer"]}}]},
    {"label": "DREAM_EVENT", "pattern": [{"LOWER": {"in": ["party", "accident", "meeting", "reunion", "escape"]}}]},
    {"label": "DREAM_ANIMAL", "pattern": [{"LOWER": {"in": ["wolf", "owl", "deer", "fox", "tiger"]}}]},
    {"label": "DREAM_INSECT", "pattern": [{"LOWER": {"in": ["moth", "beetle", "fly", "mosquito", "caterpillar"]}}]},
    {"label": "DREAM_FOOD", "pattern": [{"LOWER": {"in": ["banana", "bread", "cheese", "wine", "chocolate"]}}]},
    {"label": "DREAM_BODY_PART", "pattern": [{"LOWER": {"in": ["eye", "mouth", "leg", "brain", "skin"]}}]},
    {"label": "DREAM_COLOR", "pattern": [{"LOWER": {"in": ["black", "white", "gray", "brown", "orange"]}}]},
    # Add more entity patterns as needed
    {"label": "DREAM_FEELING", "pattern": [{"LOWER": {"in": ["loneliness", "excitement", "tension", "calmness", "curiosity"]}}]},
    {"label": "DREAM_ELEMENT", "pattern": [{"LOWER": {"in": ["mountain", "lake", "river", "wind", "storm", "cloud"]}}]},
    {"label": "DREAM_OBJECT", "pattern": [{"LOWER": {"in": ["bag", "shoes", "hat", "glasses", "watch", "ring"]}}]},
    {"label": "DREAM_EVENT", "pattern": [{"LOWER": {"in": ["birth", "death", "falling", "rescue", "escape"]}}]},
    {"label": "DREAM_ANIMAL", "pattern": [{"LOWER": {"in": ["bird", "fish", "butterfly", "frog", "turtle", "whale"]}}]},
    {"label": "DREAM_INSECT", "pattern": [{"LOWER": {"in": ["fly", "moth", "dragonfly", "beetle", "grasshopper"]}}]},
    {"label": "DREAM_FOOD", "pattern": [{"LOWER": {"in": ["bread", "cake", "soup", "fruit", "vegetable", "meat"]}}]},
    {"label": "DREAM_BODY_PART", "pattern": [{"LOWER": {"in": ["arm", "finger", "ear", "shoulder", "back"]}}]},
    {"label": "DREAM_COLOR", "pattern": [{"LOWER": {"in": ["pink", "violet", "cyan", "magenta", "indigo"]}}]},
    # Add more entity patterns as needed
]
